// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1HYXquE5wKYkL1ZUWwta_7o2UL8Ek7qs',
    appId: '1:67275469692:web:7e07315e828d7ad068aaf9',
    messagingSenderId: '67275469692',
    projectId: 'suratconnect-4a1bc',
    authDomain: 'suratconnect-4a1bc.firebaseapp.com',
    storageBucket: 'suratconnect-4a1bc.firebasestorage.app',
    measurementId: 'G-ZMJWMTRCPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4GBpfKZonv87mAV3xFgbt61aujTl8KLI',
    appId: '1:67275469692:android:108fbf396075e57568aaf9',
    messagingSenderId: '67275469692',
    projectId: 'suratconnect-4a1bc',
    storageBucket: 'suratconnect-4a1bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Fc-Hxlyz4zCPuE_7DCDZwSu29XWFlwc',
    appId: '1:67275469692:ios:256e182d9e1f5b9c68aaf9',
    messagingSenderId: '67275469692',
    projectId: 'suratconnect-4a1bc',
    storageBucket: 'suratconnect-4a1bc.firebasestorage.app',
    iosClientId: '67275469692-d91br8pan91lnm4of16k0i5lf0kk5qgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Fc-Hxlyz4zCPuE_7DCDZwSu29XWFlwc',
    appId: '1:67275469692:ios:256e182d9e1f5b9c68aaf9',
    messagingSenderId: '67275469692',
    projectId: 'suratconnect-4a1bc',
    storageBucket: 'suratconnect-4a1bc.firebasestorage.app',
    iosClientId: '67275469692-d91br8pan91lnm4of16k0i5lf0kk5qgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1HYXquE5wKYkL1ZUWwta_7o2UL8Ek7qs',
    appId: '1:67275469692:web:f81106c225d1d43768aaf9',
    messagingSenderId: '67275469692',
    projectId: 'suratconnect-4a1bc',
    authDomain: 'suratconnect-4a1bc.firebaseapp.com',
    storageBucket: 'suratconnect-4a1bc.firebasestorage.app',
    measurementId: 'G-0XYJD3002D',
  );

}